### ISSUE TITLE
Install instructions has a horizontal and vertical scrollbar

### ISSUE THREAD

**Issue by ahayzen** [jgarciao/linux-store-frontend#2]
What happened:
1) Go to the demo page
2) Go to the list of applications
3) Click on an application and scroll down to the bottom
4) Change install instructions to "Command line"
5) Notice that there is both horizontal and vertical scrollbars

What I expected to happen:
At step 5 I expected only the horizontal scrollbar to be visible and for the content not to be limited in height. Note if you switch to "Click to download" the vertical height is actually larger.

![screenshot from 2017-09-28 21-46-36](https://user-images.githubusercontent.com/3669750/30989758-b641e3c8-a496-11e7-8a10-51e597ad76f8.png)

**Comment by jgarciao** [comment]
The current release got rid of the "Click to download" and "Comand line" tabs and now everything is more readable, even on mobile devices. Still  work to do (it's a little too verbose) but good enough in my opinion

Thanks for your feedback!
