### ISSUE TITLE
Add Google Analytics

### ISSUE THREAD

**Issue by jgarciao** [jgarciao/linux-store-frontend#22]

**Comment by Alexander-Wilms** [comment]
Would the benefits outweigh the downsides? I think the average Flathub user would object to any tracking.

**Comment by jgarciao** [comment]
I've never used Google Analytics before but the reason I want to use it is to help me answer this questions:
* How many people is using this website? Where do they come from? What are they looking for?
* How can the website be improved to help users find what they want?
* How can the website be improved to increase donations to developers?
* (Eventually) How can the website be improved to increase app purchases?
* (Eventually) How can the website be improved to increase donations to Flathub?

Something that sould be added at the same time is a Privacy policy page informing about the information collected and how to enable tracking protection

**Comment by Zig-03** [comment]
One year has passed, do you still need more data to help you make decisions?

**Comment by jgarciao** [comment]
Yes. For the same reasons I wrote a year ago. Also to decide if it's worth my spare time to work on this project
