### ISSUE TITLE
When there is one screenshot, clicking on it results in loading animation

### ISSUE THREAD

**Issue by ahayzen** [jgarciao/linux-store-frontend#35]
What happened:
1) Navigate to an app that only has one screenshot, eg gedit [0]
2) Click on the larger screenshot
3) Notice how a loading animation appears and never finishes (see screenshot below).

What I expected to happen:
At step 3 for the same image to be shown as there is only one.

Note: That clicking on the larger screenshot, when there are multiple, cycles through the screenshots.

0 - https://beta.flathub.org/apps/details/org.gnome.gedit

![image](https://user-images.githubusercontent.com/3669750/34892553-9a02b30c-f7d1-11e7-9c51-447e3540014d.png)

**Comment by jgarciao** [comment]
I think is a bug in the ng-gallery component. I've asked for help there https://github.com/MurhafSousli/ng-gallery/issues/52
