### ISSUE TITLE
App description tooltips aren't great

### ISSUE THREAD

**Issue by allanday** [jgarciao/linux-store-frontend#42]
When you hover over an app tile, a tooltip is shown with the full description. This isn't great for a few reasons - it repeats the description that's already shown above, and it's distracting.

A better solution would be to increase the amount of space for the descriptions in the tiles.

I observed this issue testing the following instance: http://45.55.104.129/home

**Comment by jgarciao** [comment]
I've removed the tooltip in the test instance

**Comment by allanday** [comment]
Thanks!
