### ISSUE TITLE
Show metadata

### ISSUE THREAD

**Issue by Alexander-Wilms** [jgarciao/linux-store-frontend#45]
Just like KDE Discover and Gnome Software, Flathub could list the version, size, license and homepage below the description.

![grafik](https://user-images.githubusercontent.com/3226457/37223040-8ab6ec4a-23cf-11e8-89d8-91b425f39c8b.png)

**Comment by jgarciao** [comment]
I'm working on improving this. I expect to publish it by the end of the month or before
