### ISSUE TITLE
App list is sorted with case sensitivity (it should be case insensitive) and apps are not shown in title case

### ISSUE THREAD

**Issue by ahayzen** [jgarciao/linux-store-frontend#6]
What happened:
1) Navigate to the applications page [0]
2) Scroll right to the bottom
3) Notice that applications starting with lowercase names are sorted after uppercase. Eg "darktable" and "gedit" are *after* "Videos" and "Weather"

What I expected to happen:
At step 3 for the applications to be sorted in a case insensitive way. Also the existing flathub site [1] shows all names in title case (first character of each word capitalised) I wonder if this site should be the same? Eg "Tux, of Math Command" becomes "Tux, Of Math Command".

# Demo Site
Notice the positioning of darktable and gedit
![screenshot from 2017-11-15 22-45-55](https://user-images.githubusercontent.com/3669750/32864375-d8320dce-ca56-11e7-8bc1-a1c54e1489ed.png)

# Existing flathub site
Notice in the existing site [1] that they are sorted case insensitive (see darktable is inbetween CuteMarkEd and Dconf Editor)
![screenshot from 2017-11-15 22-46-11](https://user-images.githubusercontent.com/3669750/32864456-28f4f87a-ca57-11e7-936d-97672cf3bcdc.png)

0 - http://45.55.104.129/apps
1 - https://flathub.org/apps.html

**Comment by jgarciao** [comment]
I still have to deploy the new version of the backend in the server but the issue is fixed now

Thank you for reporting it!
